"""Strategy Engine V1.0 domain models and evaluation layers."""

from data.models import Timeframe
from strategies.allocation_resolver import resolve_allocations
from strategies.condition_evaluator import evaluate_condition
from strategies.enums import (
    AllocationSource,
    AssetRole,
    ComparisonOperator,
    LogicalOperator,
    NoMatchBehavior,
    OperandType,
    RebalanceFrequency,
    StrategyEvaluationMode,
    StrategyEvaluationStatus,
    StrategyStatus,
    ThresholdType,
)
from strategies.evaluation import (
    ConditionResult,
    EvaluationContext,
    IndicatorKey,
    OperandValue,
    RuleGroupResult,
    TargetAllocationResult,
)
from strategies.exceptions import UnsupportedTimeframeError
from strategies.models import (
    CURRENT_STRATEGY_SCHEMA_VERSION,
    LEGACY_STRATEGY_SCHEMA_VERSION,
    Allocation,
    AllocationRule,
    AllocationSpecification,
    AssetReference,
    Condition,
    FallbackAllocation,
    Operand,
    RebalancePolicy,
    RegimeDefinition,
    RegimeTransitionDefinition,
    RemainingAllocation,
    RuleGroup,
    StrategyAssetReference,
    StrategyDefinition,
    StrategyMaterializationProvenance,
    StrategyVersion,
    Threshold,
)
from strategies.operand_evaluator import evaluate_operand
from strategies.regime import (
    RegimeRuntimeState,
    RegimeTransitionEvent,
    RegimeTransitionEvidence,
    evaluate_regime_strategy,
)
from strategies.rule_group_evaluator import evaluate_rule_group
from strategies.signal_engine import StrategySignal, build_signal
from strategies.strategy_evaluation import (
    EvaluationFailure,
    StrategyEvaluationResult,
    StrategyEvaluationTimeline,
    evaluate_strategy,
    required_indicators,
    required_weekly_assets,
)
from strategies.validation import (
    StrategyValidator,
    ValidationCode,
    ValidationIssue,
    ValidationResult,
    validate_strategy,
    validate_strategy_definition,
)

__all__ = [
    "Allocation",
    "AllocationSpecification",
    "AllocationSource",
    "AllocationRule",
    "AssetReference",
    "AssetRole",
    "StrategyAssetReference",
    "CURRENT_STRATEGY_SCHEMA_VERSION",
    "LEGACY_STRATEGY_SCHEMA_VERSION",
    "Timeframe",
    "UnsupportedTimeframeError",
    "ComparisonOperator",
    "Condition",
    "ConditionResult",
    "EvaluationContext",
    "EvaluationFailure",
    "FallbackAllocation",
    "LogicalOperator",
    "NoMatchBehavior",
    "Operand",
    "OperandType",
    "OperandValue",
    "IndicatorKey",
    "RuleGroupResult",
    "TargetAllocationResult",
    "RebalanceFrequency",
    "RebalancePolicy",
    "RemainingAllocation",
    "RuleGroup",
    "RegimeDefinition",
    "RegimeTransitionDefinition",
    "StrategyDefinition",
    "StrategyMaterializationProvenance",
    "StrategyEvaluationResult",
    "StrategyEvaluationStatus",
    "StrategyEvaluationMode",
    "StrategyEvaluationTimeline",
    "StrategyStatus",
    "StrategyVersion",
    "Threshold",
    "ThresholdType",
    "StrategyValidator",
    "ValidationCode",
    "ValidationIssue",
    "ValidationResult",
    "validate_strategy",
    "validate_strategy_definition",
    "evaluate_condition",
    "evaluate_operand",
    "evaluate_rule_group",
    "StrategySignal",
    "build_signal",
    "resolve_allocations",
    "evaluate_strategy",
    "required_indicators",
    "required_weekly_assets",
    "RegimeRuntimeState",
    "RegimeTransitionEvent",
    "RegimeTransitionEvidence",
    "evaluate_regime_strategy",
]
