"""PHASE 8A research domain contracts."""

from research.candidates import ParameterCandidateSet, generate_candidates
from research.canonical import canonical_json, sha256_hash
from research.enums import (
    ConstraintOperator,
    ExperimentMethod,
    ExperimentStatus,
    MetricDirection,
    ParameterType,
)
from research.exceptions import (
    CandidateGenerationError,
    ExperimentDomainError,
    ExperimentNotFrozenError,
    InvalidExperimentError,
    InvalidExperimentProvenanceError,
    InvalidObjectiveSpecificationError,
    InvalidParameterBindingError,
    InvalidParameterConstraintError,
    InvalidParameterDefinitionError,
    InvalidParameterSetError,
    InvalidParameterSpaceError,
    ParameterBindingError,
    ParameterBindingTypeMismatchError,
    ParameterSpaceTooLargeError,
    StrategyMaterializationError,
    UnsupportedParameterBindingTargetError,
)
from research.experiments import (
    Experiment,
    ExperimentProvenance,
    ObjectiveSpecification,
    ParameterConstraint,
    ParameterDefinition,
    ParameterSet,
    ParameterSpace,
)
from research.materialization import (
    BindingValueType,
    ParameterBinding,
    ParameterBindingSet,
    materialize_strategy_version,
)

__all__ = [
    "ConstraintOperator",
    "CandidateGenerationError",
    "canonical_json",
    "Experiment",
    "ExperimentDomainError",
    "ExperimentMethod",
    "ExperimentNotFrozenError",
    "ExperimentProvenance",
    "ExperimentStatus",
    "InvalidExperimentError",
    "InvalidExperimentProvenanceError",
    "InvalidObjectiveSpecificationError",
    "InvalidParameterConstraintError",
    "InvalidParameterDefinitionError",
    "InvalidParameterSetError",
    "InvalidParameterSpaceError",
    "MetricDirection",
    "ObjectiveSpecification",
    "ParameterConstraint",
    "ParameterCandidateSet",
    "ParameterDefinition",
    "ParameterSet",
    "ParameterSpace",
    "ParameterSpaceTooLargeError",
    "ParameterType",
    "BindingValueType",
    "InvalidParameterBindingError",
    "ParameterBinding",
    "ParameterBindingError",
    "ParameterBindingSet",
    "ParameterBindingTypeMismatchError",
    "StrategyMaterializationError",
    "UnsupportedParameterBindingTargetError",
    "materialize_strategy_version",
    "sha256_hash",
    "generate_candidates",
]
