"""Deterministic target-allocation backtest engine."""

from backtest.contributions import normalize_contribution_schedule
from backtest.engine import BacktestEngine
from backtest.integration import (
    StrategyBacktestAllocation,
    StrategyBacktestResult,
    run_strategy_backtest,
    target_allocations_from_timeline,
)
from backtest.models import (
    AllocationConstraint,
    AllocationPoint,
    BacktestConfig,
    BacktestResult,
    CommissionPolicy,
    ContributionEvent,
    ContributionFrequency,
    ContributionSchedule,
    EquityPoint,
    ExecutionRule,
    ExternalCashFlow,
    Fill,
    HoldingSegment,
    HoldingStatus,
    Order,
    OrderSide,
    OrderStatus,
    PositionRebalancePolicy,
    RebalanceCause,
    RebalanceDecision,
    RebalanceDecisionType,
    RebalanceFrequency,
    RebalancePolicy,
    RebalanceSuppressionReason,
    TargetAllocation,
    TargetWeight,
    Trade,
)

__all__ = [
    "AllocationPoint",
    "AllocationConstraint",
    "BacktestConfig",
    "BacktestEngine",
    "BacktestResult",
    "CommissionPolicy",
    "ContributionEvent",
    "ContributionFrequency",
    "ContributionSchedule",
    "EquityPoint",
    "ExecutionRule",
    "Fill",
    "HoldingSegment",
    "HoldingStatus",
    "ExternalCashFlow",
    "Order",
    "OrderSide",
    "OrderStatus",
    "RebalanceFrequency",
    "RebalanceCause",
    "RebalanceDecision",
    "RebalanceDecisionType",
    "RebalancePolicy",
    "RebalanceSuppressionReason",
    "PositionRebalancePolicy",
    "TargetAllocation",
    "TargetWeight",
    "Trade",
    "StrategyBacktestAllocation",
    "StrategyBacktestResult",
    "run_strategy_backtest",
    "target_allocations_from_timeline",
    "normalize_contribution_schedule",
]
